### ISSUE TITLE
external router

### ISSUE THREAD

**Issue by buckitupnet** [Buckitup-chat/chat#99]
Add an option of adding an external router (which one?) to the system, so that the bigger range and better wifi standards supported.

**Comment by sergey-lukianov** [comment]
The idea is to plug RPi into external port of a router. Instead of internet connection. This way router can be configured to better WiFi standards
@buckitupnet  RPi has 1000Mbit port. so the best router would provide 1000Mbit. It is likely to be dual range WiFi router (2.4GHz and 5GHz). Every modern router supports WPA3 (It might be state on the box but unlikely).

Ethernet interface on RPi is configured to accept DHCP configuration. It needs to be changed to provide DHCP configuration the same way as we do for WiFi,
